name: Setup

inputs:
  gcp_credentials_json:
    description: GCP Role Access
    required: true
  gcp_registry_username:
    description: GCP registry user
    required: true
  ssh-private-key:
    description: SSH Private Key
    required: true

outputs:
  kamal-registry-password:
    description: Kamal Registry Password
    value: ${{ steps.auth.outputs.access_token }}

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: ./Gemfile
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: access_token
        credentials_json: '${{ inputs.gcp_credentials_json }}'

    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v3'
      with:
        username: '${{ inputs.gcp_registry_username }}'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '<gcp_registry>'
