# Name of your application. Used to uniquely configure containers.
service: <your-service-name>

# Name of the container image.
image: <your-image-name>

# Use a different ssh user than root
ssh:
  user: www

# Credentials for your image host.
registry:
  server: us-central1-docker.pkg.dev/<%=PROJECT_ID%>/reponame

  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Container builder setup.
builder:
  arch: amd64
  args:
    RUBY_VERSION: <%= File.read('.ruby-version').strip %>
    # NODE_VERSION: 18.15.0
    # YARN_VERSION: 1.22.21
  cache:
    type: registry
    options: mode=max,image-manifest=true,oci-mediatypes=true

env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - REDIS_URL

accessories:
  redis:
    image: "redis:alpine"
    roles:
       - sidekiq
    volumes:
      - ~/docker_redis_data:/data